In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit

In [2]:
from sklearn.datasets import load_boston

In [3]:
data = load_boston()
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [4]:
X = data.data
y = data.target

In [5]:
X.shape

(506, 13)

In [6]:
y.shape

(506,)

In [7]:
pd.DataFrame(X)

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [8]:
from sklearn.linear_model import SGDRegressor

In [9]:
regr = SGDRegressor()

In [10]:
X_train = X[:-100]
y_train = y[:-100]
X_test = X[-100:]
y_test = y[-100:]

In [11]:
regr.fit(X_train, y_train)

SGDRegressor()

In [12]:
from sklearn.metrics import r2_score

In [13]:
y_pred = regr.predict(X_test)
y_pred

array([-9.74817060e+13, -8.76869042e+13, -7.81402075e+13, -6.28334135e+13,
       -6.33659703e+13, -3.90326298e+13, -3.84073188e+13, -7.82747123e+13,
       -6.66530549e+13, -3.87275534e+13, -3.39125404e+13, -6.18413516e+13,
       -7.89873719e+13, -4.05167333e+13, -8.40787026e+13, -8.15123109e+13,
       -8.14479614e+13, -2.91861010e+13, -3.30698285e+13, -3.54989471e+13,
       -3.98832894e+13, -5.63439638e+13, -4.53849460e+13, -3.93390228e+13,
       -4.45575241e+13, -4.42895750e+13, -4.74681504e+13, -4.53955121e+13,
       -5.13368723e+13, -4.87650737e+13, -3.92878569e+13, -3.44523292e+13,
       -4.17731249e+13, -9.38928741e+13, -1.02358931e+14, -9.29232141e+13,
       -9.21779422e+13, -9.32189886e+13, -7.08005956e+13, -3.75174305e+13,
       -8.00303418e+13, -9.43098075e+13, -9.46909732e+13, -7.81986201e+13,
       -2.95452222e+13, -8.52788512e+13, -9.03471798e+13, -9.06844647e+13,
       -3.21692531e+13, -3.64701404e+13, -2.96849335e+13, -3.20606368e+13,
       -7.48451692e+13, -

In [14]:
r2_score(y_test, y_pred)

-2.2294799410798822e+26

In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
st = StandardScaler()

In [17]:
X_scaled =  st.fit_transform(X_train)

In [18]:
pd.DataFrame(X_scaled)

0         1         2         3         4         5         6   \
0   -0.298267  0.152053 -1.106251 -0.307148  0.047750  0.335796  0.021822   
1   -0.295382 -0.561171 -0.378402 -0.307148 -0.554183  0.125127  0.493935   
2   -0.295385 -0.561171 -0.378402 -0.307148 -0.554183  1.170265 -0.119467   
3   -0.294686 -0.561171 -1.126129 -0.307148 -0.650143  0.914452 -0.646717   
4   -0.289644 -0.561171 -1.126129 -0.307148 -0.650143  1.118282 -0.357246   
..        ...       ...       ...       ...       ...       ...       ...   
401  1.657886 -0.561171  1.308189 -0.307148  1.399919  0.018424  1.221058   
402  1.019967 -0.561171  1.308189 -0.307148  1.399919  0.101871  1.221058   
403  3.110304 -0.561171  1.308189 -0.307148  1.399919 -1.341350  1.083215   
404  5.409801 -0.561171  1.308189 -0.307148  1.399919 -1.092378  0.717930   
405  9.037801 -0.561171  1.308189 -0.307148  1.399919 -0.884444  1.221058   

           7         8         9         10        11        12  
0   -0.032605 -0.891237 -0.439870 -1.234403  0.421317 -0.938068  
1    0.369493 -0.739521 -0.846228 -0.106866  0.421317 -0.332398  
2    0.369493 -0.739521 -0.846228 -0.106866  0.320688 -1.076382  
3    0.871531 -0.587806 -0.996731  0.299047  0.365192 -1.235079  
4    0.871531 -0.587806 -0.996731  0.299047  0.421317 -0.887110  
..        ...       ...       ...       ...       ...       ...  
401 -1.185995  2.598228  2.344439  0.975570  0.421317  1.295339  
402 -1.156242  2.598228  2.344439  0.975570 -0.092709  1.293883  
403 -1.126993  2.598228  2.344439  0.975570  0.421317  1.215262  
404 -1.170729  2.598228  2.344439  0.975570 -1.246117  2.323230  
405 -1.254165  2.598228  2.344439  0.975570  0.126352  1.682618  

[406 rows x 13 columns]

In [19]:
data = pd.read_csv("./archive/train.csv")

In [20]:
pd.set_option('display.max_columns', None)

In [21]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

In [22]:
numerical = data[["MSSubClass", "LotFrontage", "LotArea", "OverallQual", "OverallCond", "YearBuilt", "YearRemodAdd", "MasVnrArea", "BsmtFinSF1", "BsmtFinSF2", "BsmtUnfSF", "TotalBsmtSF", "1stFlrSF", "2ndFlrSF", "LowQualFinSF", "GrLivArea", "BsmtFullBath", "BsmtHalfBath", "FullBath", "HalfBath", "BedroomAbvGr", "KitchenAbvGr", "TotRmsAbvGrd", "Fireplaces", "GarageYrBlt", "GarageCars", "GarageArea", "WoodDeckSF", "OpenPorchSF", "EnclosedPorch", "3SsnPorch", "ScreenPorch", "PoolArea", "MiscVal", "MoSold", "YrSold"]]

In [23]:
numerical.isna().sum()

MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [24]:
numerical = numerical.copy()

In [25]:
numerical["LotFrontage"] = numerical["LotFrontage"].fillna(-1)

In [26]:
numerical.isna().sum()

MSSubClass        0
LotFrontage       0
LotArea           0
OverallQual       0
OverallCond       0
YearBuilt         0
YearRemodAdd      0
MasVnrArea        8
BsmtFinSF1        0
BsmtFinSF2        0
BsmtUnfSF         0
TotalBsmtSF       0
1stFlrSF          0
2ndFlrSF          0
LowQualFinSF      0
GrLivArea         0
BsmtFullBath      0
BsmtHalfBath      0
FullBath          0
HalfBath          0
BedroomAbvGr      0
KitchenAbvGr      0
TotRmsAbvGrd      0
Fireplaces        0
GarageYrBlt      81
GarageCars        0
GarageArea        0
WoodDeckSF        0
OpenPorchSF       0
EnclosedPorch     0
3SsnPorch         0
ScreenPorch       0
PoolArea          0
MiscVal           0
MoSold            0
YrSold            0
dtype: int64

In [27]:
numerical = numerical.copy()

In [28]:
numerical["MasVnrArea"] = numerical["MasVnrArea"].fillna(-1)

In [29]:
numerical = numerical.copy()

In [30]:
numerical["GarageYrBlt"] = numerical["GarageYrBlt"].fillna(-1)

In [31]:
numerical.isna().sum()

MSSubClass       0
LotFrontage      0
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
YearRemodAdd     0
MasVnrArea       0
BsmtFinSF1       0
BsmtFinSF2       0
BsmtUnfSF        0
TotalBsmtSF      0
1stFlrSF         0
2ndFlrSF         0
LowQualFinSF     0
GrLivArea        0
BsmtFullBath     0
BsmtHalfBath     0
FullBath         0
HalfBath         0
BedroomAbvGr     0
KitchenAbvGr     0
TotRmsAbvGrd     0
Fireplaces       0
GarageYrBlt      0
GarageCars       0
GarageArea       0
WoodDeckSF       0
OpenPorchSF      0
EnclosedPorch    0
3SsnPorch        0
ScreenPorch      0
PoolArea         0
MiscVal          0
MoSold           0
YrSold           0
dtype: int64

In [32]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

In [33]:
listOfCatCol = ["MSZoning", "Street", "LotShape", "LandContour", "Utilities", "LotConfig", "LandSlope", "Neighborhood", "Condition1", "Condition2", "BldgType", "HouseStyle", "RoofStyle", "RoofMatl", "Exterior1st", "Exterior2nd", "MasVnrType", "ExterQual", "ExterCond", "Foundation", "BsmtQual", "BsmtCond", "BsmtExposure", "BsmtFinType1", "BsmtFinType2", "Heating", "HeatingQC", "CentralAir", "Electrical", "KitchenQual", "Functional", "GarageType", "GarageFinish", "GarageCond", "PavedDrive", "SaleType", "SaleCondition"]
categorical = data[listOfCatCol]

In [34]:
categorical.isna().sum()

MSZoning          0
Street            0
LotShape          0
LandContour       0
Utilities         0
LotConfig         0
LandSlope         0
Neighborhood      0
Condition1        0
Condition2        0
BldgType          0
HouseStyle        0
RoofStyle         0
RoofMatl          0
Exterior1st       0
Exterior2nd       0
MasVnrType        8
ExterQual         0
ExterCond         0
Foundation        0
BsmtQual         37
BsmtCond         37
BsmtExposure     38
BsmtFinType1     37
BsmtFinType2     38
Heating           0
HeatingQC         0
CentralAir        0
Electrical        1
KitchenQual       0
Functional        0
GarageType       81
GarageFinish     81
GarageCond       81
PavedDrive        0
SaleType          0
SaleCondition     0
dtype: int64

In [35]:
categorical["BsmtCond"].unique()

array(['TA', 'Gd', nan, 'Fa', 'Po'], dtype=object)

In [36]:
from sklearn.preprocessing import OneHotEncoder

In [37]:
X = numerical.to_numpy()
y = data["SalePrice"].to_numpy()

X.shape, y.shape

((1460, 36), (1460,))

In [38]:
from sklearn.linear_model import LinearRegression

In [39]:
lr = LinearRegression()

In [40]:
X_train = X[:1200]
y_train = y[:1200]
X_test = X[1200:]
y_test = y[1200:]

In [41]:
st = StandardScaler()

In [42]:
X_train

array([[6.0000e+01, 6.5000e+01, 8.4500e+03, ..., 0.0000e+00, 2.0000e+00,
        2.0080e+03],
       [2.0000e+01, 8.0000e+01, 9.6000e+03, ..., 0.0000e+00, 5.0000e+00,
        2.0070e+03],
       [6.0000e+01, 6.8000e+01, 1.1250e+04, ..., 0.0000e+00, 9.0000e+00,
        2.0080e+03],
       ...,
       [7.5000e+01, 6.5000e+01, 8.8500e+03, ..., 0.0000e+00, 7.0000e+00,
        2.0060e+03],
       [2.0000e+01, 7.0000e+01, 9.1000e+03, ..., 0.0000e+00, 6.0000e+00,
        2.0090e+03],
       [2.0000e+01, 7.5000e+01, 1.1235e+04, ..., 0.0000e+00, 1.0000e+01,
        2.0060e+03]])

In [43]:
X_scale = st.fit_transform(X_train)

In [44]:
lr.fit(X_scale, y_train)

LinearRegression()

In [45]:
lr.score(st.transform(X_test), y_test)

0.4875527991516213

In [46]:
categorical = categorical.copy()

In [47]:

for col in listOfCatCol:
    categorical[col].fillna('', inplace=True)

categorical

MSZoning Street LotShape LandContour Utilities LotConfig LandSlope  \
0          RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1          RL   Pave      Reg         Lvl    AllPub       FR2       Gtl   
2          RL   Pave      IR1         Lvl    AllPub    Inside       Gtl   
3          RL   Pave      IR1         Lvl    AllPub    Corner       Gtl   
4          RL   Pave      IR1         Lvl    AllPub       FR2       Gtl   
...       ...    ...      ...         ...       ...       ...       ...   
1455       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1456       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1457       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1458       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   
1459       RL   Pave      Reg         Lvl    AllPub    Inside       Gtl   

     Neighborhood Condition1 Condition2 BldgType HouseStyle RoofStyle  \
0         CollgCr       Norm       Norm     1Fam     2Story     Gable   
1         Veenker      Feedr       Norm     1Fam     1Story     Gable   
2         CollgCr       Norm       Norm     1Fam     2Story     Gable   
3         Crawfor       Norm       Norm     1Fam     2Story     Gable   
4         NoRidge       Norm       Norm     1Fam     2Story     Gable   
...           ...        ...        ...      ...        ...       ...   
1455      Gilbert       Norm       Norm     1Fam     2Story     Gable   
1456       NWAmes       Norm       Norm     1Fam     1Story     Gable   
1457      Crawfor       Norm       Norm     1Fam     2Story     Gable   
1458        NAmes       Norm       Norm     1Fam     1Story       Hip   
1459      Edwards       Norm       Norm     1Fam     1Story     Gable   

     RoofMatl Exterior1st Exterior2nd MasVnrType ExterQual ExterCond  \
0     CompShg     VinylSd     VinylSd    BrkFace        Gd        TA   
1     CompShg     MetalSd     MetalSd       None        TA        TA   
2     CompShg     VinylSd     VinylSd    BrkFace        Gd        TA   
3     CompShg     Wd Sdng     Wd Shng       None        TA        TA   
4     CompShg     VinylSd     VinylSd    BrkFace        Gd        TA   
...       ...         ...         ...        ...       ...       ...   
1455  CompShg     VinylSd     VinylSd       None        TA        TA   
1456  CompShg     Plywood     Plywood      Stone        TA        TA   
1457  CompShg     CemntBd     CmentBd       None        Ex        Gd   
1458  CompShg     MetalSd     MetalSd       None        TA        TA   
1459  CompShg     HdBoard     HdBoard       None        Gd        TA   

     Foundation BsmtQual BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2  \
0         PConc       Gd       TA           No          GLQ          Unf   
1        CBlock       Gd       TA           Gd          ALQ          Unf   
2         PConc       Gd       TA           Mn          GLQ          Unf   
3        BrkTil       TA       Gd           No          ALQ          Unf   
4         PConc       Gd       TA           Av          GLQ          Unf   
...         ...      ...      ...          ...          ...          ...   
1455      PConc       Gd       TA           No          Unf          Unf   
1456     CBlock       Gd       TA           No          ALQ          Rec   
1457      Stone       TA       Gd           No          GLQ          Unf   
1458     CBlock       TA       TA           Mn          GLQ          Rec   
1459     CBlock       TA       TA           No          BLQ          LwQ   

     Heating HeatingQC CentralAir Electrical KitchenQual Functional  \
0       GasA        Ex          Y      SBrkr          Gd        Typ   
1       GasA        Ex          Y      SBrkr          TA        Typ   
2       GasA        Ex          Y      SBrkr          Gd        Typ   
3       GasA        Gd          Y      SBrkr          Gd        Typ   
4       GasA        Ex          Y      SBrkr          Gd        Typ   
...      ...       ... 

In [48]:
ohe = OneHotEncoder(sparse=False)

In [49]:
cats = ohe.fit_transform(categorical)

In [50]:
X_cat_train = cats[:1200]
X_cat_test = cats[1200:]

In [51]:
X_cat_train.shape, X_cat_test.shape

((1200, 239), (260, 239))

In [52]:
cats[10]

array([0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 0., 0.

In [53]:
ohe.categories_

[array(['C (all)', 'FV', 'RH', 'RL', 'RM'], dtype=object),
 array(['Grvl', 'Pave'], dtype=object),
 array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object),
 array(['Bnk', 'HLS', 'Low', 'Lvl'], dtype=object),
 array(['AllPub', 'NoSeWa'], dtype=object),
 array(['Corner', 'CulDSac', 'FR2', 'FR3', 'Inside'], dtype=object),
 array(['Gtl', 'Mod', 'Sev'], dtype=object),
 array(['Blmngtn', 'Blueste', 'BrDale', 'BrkSide', 'ClearCr', 'CollgCr',
        'Crawfor', 'Edwards', 'Gilbert', 'IDOTRR', 'MeadowV', 'Mitchel',
        'NAmes', 'NPkVill', 'NWAmes', 'NoRidge', 'NridgHt', 'OldTown',
        'SWISU', 'Sawyer', 'SawyerW', 'Somerst', 'StoneBr', 'Timber',
        'Veenker'], dtype=object),
 array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNe',
        'RRNn'], dtype=object),
 array(['Artery', 'Feedr', 'Norm', 'PosA', 'PosN', 'RRAe', 'RRAn', 'RRNn'],
       dtype=object),
 array(['1Fam', '2fmCon', 'Duplex', 'Twnhs', 'TwnhsE'], dtype=object),
 array(['1.5Fin', '1.5Unf', '1Story', '2.

In [54]:
X_train, X_cat_train

(array([[6.0000e+01, 6.5000e+01, 8.4500e+03, ..., 0.0000e+00, 2.0000e+00,
         2.0080e+03],
        [2.0000e+01, 8.0000e+01, 9.6000e+03, ..., 0.0000e+00, 5.0000e+00,
         2.0070e+03],
        [6.0000e+01, 6.8000e+01, 1.1250e+04, ..., 0.0000e+00, 9.0000e+00,
         2.0080e+03],
        ...,
        [7.5000e+01, 6.5000e+01, 8.8500e+03, ..., 0.0000e+00, 7.0000e+00,
         2.0060e+03],
        [2.0000e+01, 7.0000e+01, 9.1000e+03, ..., 0.0000e+00, 6.0000e+00,
         2.0090e+03],
        [2.0000e+01, 7.5000e+01, 1.1235e+04, ..., 0.0000e+00, 1.0000e+01,
         2.0060e+03]]),
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        ...,
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 1., 0.]]))

In [55]:
X_tr = np.hstack((X_train, X_cat_train))
X_te = np.hstack((X_test, X_cat_test))

X_tr = st.fit_transform(X_tr)
X_te = st.transform(X_te)

X_te

array([[-0.86899505,  0.38667456, -0.1136547 , ..., -0.11987596,
        -2.10472427, -0.30804303],
       [ 0.06855861,  0.64728896, -0.015018  , ..., -0.11987596,
         0.47512162, -0.30804303],
       [-0.1658298 , -0.22142572, -0.42953709, ..., -0.11987596,
         0.47512162, -0.30804303],
       ...,
       [ 0.30294703,  0.24188878, -0.14295366, ..., -0.11987596,
         0.47512162, -0.30804303],
       [-0.86899505,  0.29980309, -0.07936266, ..., -0.11987596,
         0.47512162, -0.30804303],
       [-0.86899505,  0.50250318, -0.05863671, ..., -0.11987596,
         0.47512162, -0.30804303]])

In [56]:
y_scaler = StandardScaler()

y_train_s = y_scaler.fit_transform(y_train.reshape(-1, 1))

y_test_s = y_scaler.transform(y_test.reshape(-1, 1))

y_train_s, y_test_s

(array([[ 0.33423413],
        [ 0.00105349],
        [ 0.51933448],
        ...,
        [-0.4616974 ],
        [-0.04213659],
        [-0.4123373 ]]),
 array([[-0.80660106],
        [ 0.20342988],
        [-0.79487804],
        [ 0.38976423],
        [-0.34446717],
        [ 1.11659162],
        [-0.91827827],
        [ 0.22934393],
        [-0.51105749],
        [ 1.33994605],
        [ 0.09360367],
        [-0.21489693],
        [-0.84423813],
        [-0.44935737],
        [-0.57892762],
        [-0.69615785],
        [-0.85657815],
        [ 0.59283166],
        [-1.2452889 ],
        [-1.10954864],
        [-0.81955808],
        [-0.58509763],
        [-0.47403742],
        [-0.53697154],
        [ 0.03190355],
        [-0.44935737],
        [ 0.40210426],
        [-0.42467733],
        [ 2.29375584],
        [-0.6714778 ],
        [ 0.10594369],
        [-0.60360767],
        [-0.9824464 ],
        [-0.48637745],
        [-0.63445773],
        [-0.52479194],
        [-0.0729866

In [57]:
lr = LinearRegression()

In [58]:
lr.fit(X_tr, y_train_s)

LinearRegression()

In [59]:
lr.score(X_te, y_test_s)

-6.217476147530895e+24

In [60]:
sgdr = SGDRegressor(max_iter=1500)

In [61]:
sgdr.fit(X_tr, y_train_s.ravel())

SGDRegressor(max_iter=1500)

In [62]:
sgdr.score(X_te, y_test_s)

-1.0714160592121318

In [63]:
from sklearn.preprocessing import Normalizer

In [64]:
nm = Normalizer()

In [65]:
X_tr = np.hstack((X_train, X_cat_train))
X_te = np.hstack((X_test, X_cat_test))

X_tr_normalizer = nm.fit_transform(X_tr)
X_te_normalizer = nm.transform(X_te)

X_tr_normalizer, X_te_normalizer

(array([[6.20635077e-03, 6.72354667e-03, 8.74061067e-01, ...,
         0.00000000e+00, 1.03439180e-04, 0.00000000e+00],
        [1.87297225e-03, 7.49188901e-03, 8.99026681e-01, ...,
         0.00000000e+00, 9.36486126e-05, 0.00000000e+00],
        [4.91417436e-03, 5.56939761e-03, 9.21407693e-01, ...,
         0.00000000e+00, 8.19029060e-05, 0.00000000e+00],
        ...,
        [7.52733032e-03, 6.52368627e-03, 8.88224977e-01, ...,
         0.00000000e+00, 1.00364404e-04, 0.00000000e+00],
        [1.94999560e-03, 6.82498460e-03, 8.87247998e-01, ...,
         0.00000000e+00, 9.74997800e-05, 0.00000000e+00],
        [1.64610624e-03, 6.17289840e-03, 9.24700181e-01, ...,
         0.00000000e+00, 8.23053120e-05, 0.00000000e+00]]),
 array([[1.94052959e-03, 6.88888003e-03, 9.07488661e-01, ...,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [5.24684917e-03, 6.99579890e-03, 9.09453857e-01, ...,
         0.00000000e+00, 8.74474862e-05, 0.00000000e+00],
        [6.67895579e-03, 

In [66]:
X_tr, X_te

(array([[6.0000e+01, 6.5000e+01, 8.4500e+03, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [2.0000e+01, 8.0000e+01, 9.6000e+03, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [6.0000e+01, 6.8000e+01, 1.1250e+04, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        ...,
        [7.5000e+01, 6.5000e+01, 8.8500e+03, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [2.0000e+01, 7.0000e+01, 9.1000e+03, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00],
        [2.0000e+01, 7.5000e+01, 1.1235e+04, ..., 0.0000e+00, 1.0000e+00,
         0.0000e+00]]),
 array([[2.000e+01, 7.100e+01, 9.353e+03, ..., 0.000e+00, 0.000e+00,
         0.000e+00],
        [6.000e+01, 8.000e+01, 1.040e+04, ..., 0.000e+00, 1.000e+00,
         0.000e+00],
        [5.000e+01, 5.000e+01, 6.000e+03, ..., 0.000e+00, 1.000e+00,
         0.000e+00],
        ...,
        [7.000e+01, 6.600e+01, 9.042e+03, ..., 0.000e+00, 1.000e+00,
         0.000e+00],
        [2.000e+01, 6.800e+01, 9.717

In [75]:
sgdr.fit(X_tr_normalizer, y_train_s.ravel())

SGDRegressor(max_iter=1500)

In [76]:
sgdr.score(X_te_normalizer, y_test_s)

0.21824365827985215