In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('archive/age_gender.csv')

In [3]:
data.head

<bound method NDFrame.head of        age  ethnicity  gender                        img_name  \
0        1          2       0  20161219203650636.jpg.chip.jpg   
1        1          2       0  20161219222752047.jpg.chip.jpg   
2        1          2       0  20161219222832191.jpg.chip.jpg   
3        1          2       0  20161220144911423.jpg.chip.jpg   
4        1          2       0  20161220144914327.jpg.chip.jpg   
...    ...        ...     ...                             ...   
23700   99          0       1  20170120221920654.jpg.chip.jpg   
23701   99          1       1  20170120134639935.jpg.chip.jpg   
23702   99          2       1  20170110182418864.jpg.chip.jpg   
23703   99          2       1  20170117195405372.jpg.chip.jpg   
23704   99          0       1  20170110182052119.jpg.chip.jpg   

                                                  pixels  
0      129 128 128 126 127 130 133 135 139 142 145 14...  
1      164 74 111 168 169 171 175 182 184 188 193 199...  
2      67 70

In [4]:
X = []
for x in data.pixels:
    pxl = x.split(" ")
    X.append([int(p) for p in pxl])
X = np.array(X)
X.shape

(23705, 2304)

In [5]:
Y = np.array(data.gender)
Y

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [6]:
X_train = X[:-100]
Y_train = Y[:-100]
X_test = X[-100:]
Y_test = Y[-100:]

print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[129 128 128 ... 146 146 146]
 [164  74 111 ... 182 170 148]
 [ 67  70  71 ... 112 111 108]
 ...
 [195 160 132 ... 220 223 219]
 [235 235 234 ...   1   1   6]
 [121 138 145 ...  89  99 130]]
[0 0 0 ... 0 0 0]
[[114 118  67 ... 181 185 188]
 [197 189 192 ...  91 141 147]
 [182 161  92 ...  59  59  63]
 ...
 [ 59  50  37 ...  98  78  78]
 [ 45 108 120 ...  32  35  35]
 [156 161 160 ... 190 184 174]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1]


In [7]:
from sklearn.linear_model import LogisticRegression

In [43]:
lr = LogisticRegression(solver='saga', penalty='elasticnet', l1_ratio=0.5)

In [44]:
lr.fit(X_train, Y_train)

c:\users\calin\desktop\ml\.venv\lib\site-packages\sklearn\linear_model\_sag.py:328: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn("The max_iter was reached which means "


LogisticRegression(l1_ratio=0.5, penalty='elasticnet', solver='saga')

In [45]:
(lr.predict(X_test) != Y_test).sum()

38