In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pit

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
b = np.ones([1,3])
b

array([[1., 1., 1.]])

In [11]:
#Boston housing dataset

In [13]:
from sklearn.datasets import load_boston

In [15]:
data = load_boston()
data

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [16]:
X = data.data
y = data.target

In [19]:
y.shape

(506,)

In [20]:
X.shape

(506, 13)

In [21]:
pd.DataFrame(X)

0     1      2    3      4      5     6       7    8      9     10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  
1    396.90  9.14  
2    392.83  4.03  
3    394.63  2.94  
4    396.90  5.33  
..      ...   ...  
501  391.99  9.67  
502  396.90  9.08  
503  396.90  5.64  
504  393.45  6.48  
505  396.90  7.88  

[506 rows x 13 columns]

In [23]:
y

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [28]:
from sklearn.linear_model import SGDRegressor

In [29]:
regr = SGDRegressor()

In [31]:
X_train = X[:-100]
y_train = y[:-100]
X_test = X[-100:]
y_test = y[-100:]

In [32]:
regr.fit(X_train, y_train)

SGDRegressor()

In [33]:
from sklearn.metrics import r2_score

In [35]:
y_pred = regr.predict(X_test)
y_pred

array([-3.22965935e+14, -3.03432827e+14, -2.95551906e+14, -2.54940696e+14,
       -2.19745689e+14, -2.06957236e+14, -2.09326519e+14, -2.74937163e+14,
       -2.47000467e+14, -2.07669620e+14, -1.99362342e+14, -2.44376519e+14,
       -2.39907972e+14, -2.06573424e+14, -2.98520856e+14, -2.95659829e+14,
       -2.88298566e+14, -1.89532558e+14, -1.88451057e+14, -1.98676071e+14,
       -1.95961917e+14, -2.13416085e+14, -2.19818138e+14, -2.11923172e+14,
       -2.16951835e+14, -2.18605926e+14, -2.18248384e+14, -2.20672501e+14,
       -2.27283319e+14, -2.29150786e+14, -2.03377490e+14, -1.99594885e+14,
       -2.17310908e+14, -3.23188885e+14, -3.29405385e+14, -3.19859517e+14,
       -3.20596385e+14, -3.20632339e+14, -2.74011201e+14, -2.06807614e+14,
       -2.94800646e+14, -3.20477568e+14, -3.23311995e+14, -2.91421556e+14,
       -1.89061116e+14, -3.06788109e+14, -3.15496905e+14, -3.15454205e+14,
       -1.93311699e+14, -2.03719830e+14, -1.90556807e+14, -1.89249867e+14,
       -2.78471827e+14, -

In [36]:
r2_score(y_test, y_pred)

-2.85547422122631e+27

In [37]:
from sklearn.preprocessing import StandardScaler

In [38]:
st = StandardScaler()

In [39]:
X_scaled =  st.fit_transform(X_train)

In [41]:
pd.DataFrame(X_scaled)

0         1         2         3         4         5         6   \
0   -0.298267  0.152053 -1.106251 -0.307148  0.047750  0.335796  0.021822   
1   -0.295382 -0.561171 -0.378402 -0.307148 -0.554183  0.125127  0.493935   
2   -0.295385 -0.561171 -0.378402 -0.307148 -0.554183  1.170265 -0.119467   
3   -0.294686 -0.561171 -1.126129 -0.307148 -0.650143  0.914452 -0.646717   
4   -0.289644 -0.561171 -1.126129 -0.307148 -0.650143  1.118282 -0.357246   
..        ...       ...       ...       ...       ...       ...       ...   
401  1.657886 -0.561171  1.308189 -0.307148  1.399919  0.018424  1.221058   
402  1.019967 -0.561171  1.308189 -0.307148  1.399919  0.101871  1.221058   
403  3.110304 -0.561171  1.308189 -0.307148  1.399919 -1.341350  1.083215   
404  5.409801 -0.561171  1.308189 -0.307148  1.399919 -1.092378  0.717930   
405  9.037801 -0.561171  1.308189 -0.307148  1.399919 -0.884444  1.221058   

           7         8         9         10        11        12  
0   -0.032605 -0.891237 -0.439870 -1.234403  0.421317 -0.938068  
1    0.369493 -0.739521 -0.846228 -0.106866  0.421317 -0.332398  
2    0.369493 -0.739521 -0.846228 -0.106866  0.320688 -1.076382  
3    0.871531 -0.587806 -0.996731  0.299047  0.365192 -1.235079  
4    0.871531 -0.587806 -0.996731  0.299047  0.421317 -0.887110  
..        ...       ...       ...       ...       ...       ...  
401 -1.185995  2.598228  2.344439  0.975570  0.421317  1.295339  
402 -1.156242  2.598228  2.344439  0.975570 -0.092709  1.293883  
403 -1.126993  2.598228  2.344439  0.975570  0.421317  1.215262  
404 -1.170729  2.598228  2.344439  0.975570 -1.246117  2.323230  
405 -1.254165  2.598228  2.344439  0.975570  0.126352  1.682618  

[406 rows x 13 columns]

In [42]:
regr = SGDRegressor()

In [43]:
regr.fit(X_scaled, y_train)

SGDRegressor()

In [44]:
X_test_scaled = st.transform(X_test)

In [45]:
regr.score(X_test_scaled, y_test)

-0.17683251211269768

In [47]:
from sklearn.preprocessing import Normalizer

In [48]:
nm = Normalizer()

In [49]:
X_norm = nm.fit_transform(X_train)

In [50]:
regr = SGDRegressor()

In [51]:
regr.fit(X_norm, y_train)

SGDRegressor()

In [52]:
X_test_norm = nm.fit_transform(X_test)

In [53]:
regr.score(X_test_norm, y_test)

0.13307619991208997

In [54]:
from sklearn.preprocessing import PolynomialFeatures

In [142]:
pf = PolynomialFeatures(degree=2)

In [143]:
testX = np.array([[1,2,3], [4,5,6]])

In [144]:
testX

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
pf.fit_transform(testX)

array([[ 1.,  1.,  2.,  3.,  1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5.,  6., 16., 20., 24., 25., 30., 36.]])

In [146]:
st = StandardScaler()

In [147]:
poly_x = pf.fit_transform(X_train)
st_x = st.fit_transform(poly_x)

In [148]:
regr = SGDRegressor()

In [149]:
regr.fit(st_x, y_train)

SGDRegressor()

In [150]:
test_data = st.transform(pf.transform(X_test))

In [151]:
regr.score(test_data, y_test)

0.20572820494563604

In [152]:
data = pd.read_csv("./archive/train.csv")

In [154]:
pd.set_option('display.max_columns', None)

In [159]:
data.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities LotConfig LandSlope Neighborhood Condition1  \
0         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
1         Lvl    AllPub       FR2       Gtl      Veenker      Feedr   
2         Lvl    AllPub    Inside       Gtl      CollgCr       Norm   
3         Lvl    AllPub    Corner       Gtl      Crawfor       Norm   
4         Lvl    AllPub       FR2       Gtl      NoRidge       Norm   

  Condition2 BldgType HouseStyle  OverallQual  OverallCond  YearBuilt  \
0       Norm     1Fam     2Story            7            5       2003   
1       Norm     1Fam     1Story            6            8       1976   
2       Norm     1Fam     2Story            7            5       2001   
3       Norm     1Fam     2Story            7            5       1915   
4       Norm     1Fam     2Story            8            5       2000   

   YearRemodAdd RoofStyle RoofMatl Exterior1st Exterior2nd MasVnrType  \
0          2003     Gable  CompShg     VinylSd     VinylSd    BrkFace   
1          1976     Gable  CompShg     MetalSd     MetalSd       None   
2          2002     Gable  CompShg     VinylSd     VinylSd    BrkFace   
3          1970     Gable  CompShg     Wd Sdng     Wd Shng       None   
4          2000     Gable  CompShg     VinylSd     VinylSd    BrkFace   

   MasVnrArea ExterQual ExterCond Foundation BsmtQual BsmtCond BsmtExposure  \
0       196.0        Gd        TA      PConc       Gd       TA           No   
1         0.0        TA        TA     CBlock       Gd       TA           Gd   
2       162.0        Gd        TA      PConc       Gd       TA           Mn   
3         0.0        TA        TA     BrkTil       TA       Gd           No   
4       350.0        Gd        TA      PConc       Gd       TA           Av   

  BsmtFinType1  BsmtFinSF1 BsmtFinType2  BsmtFinSF2  BsmtUnfSF  TotalBsmtSF  \
0          GLQ         706          Unf           0        150          856   
1          ALQ         978          Unf           0        284         1262   
2          GLQ         486          Unf           0        434          920   
3          ALQ         216          Unf           0        540          756   
4          GLQ         655          Unf           0        490         1145   

  Heating HeatingQC CentralAir Electrical  1stFlrSF  2ndFlrSF  LowQualFinSF  \
0    GasA        Ex          Y      SBrkr       856       854             0   
1    GasA        Ex          Y      SBrkr      1262         0             0   
2    GasA        Ex          Y      SBrkr       920       866             0   
3    GasA        Gd          Y      SBrkr       961       756             0   
4    GasA        Ex          Y      SBrkr      1145      1053             0   

   GrLivArea  BsmtFullBath  BsmtHalfBath  FullBath  HalfBath  BedroomAbvGr  \
0       1710             1             0         2         1             3   
1       1262             0             1         2         0             3   
2       1786             1             0         2         1             3   
3       1717             1             0         1         0             3   
4       2198             1             0         2         1             4   

   KitchenAbvGr KitchenQual  TotRmsAbvGrd Functional  Fireplaces FireplaceQu  \
0             1          Gd             8        Typ           0         NaN   
1             1          TA             6        Typ           1          TA   
2             1          Gd             6        Typ           1          TA   
3             1          Gd            

In [216]:
numerical = data[["MSSubClass", "LotFrontage", "LotArea", "OverallQual", "OverallCond", "YearBuilt"]]
categorical = data[["MSZoning", "Street", "LotShape", "LandContour", "Utilities"]]

In [220]:
categorical.isna().sum()

MSZoning       0
Street         0
LotShape       0
LandContour    0
Utilities      0
dtype: int64

In [222]:
categorical["LotShape"].unique()

array(['Reg', 'IR1', 'IR2', 'IR3'], dtype=object)

In [223]:
from sklearn.preprocessing import OneHotEncoder

In [204]:
X = numerical.to_numpy()
y = data["SalePrice"].to_numpy()

X.shape, y.shape

((1460, 6), (1460,))

In [205]:
from sklearn.linear_model import LinearRegression

In [206]:
lr = LinearRegression()

In [207]:
X_train = X[:1200]
y_train = y[:1200]
X_test = X[1200:]
y_test = y[1200:]

In [208]:
st = StandardScaler()

In [209]:
X_scale = st.fit_transform(X_train)

In [210]:
lr.fit(X_scale, y_train)

LinearRegression()

In [190]:
numerical.isna().sum()

MSSubClass       0
LotFrontage    259
LotArea          0
OverallQual      0
OverallCond      0
YearBuilt        0
dtype: int64

In [193]:
numerical = numerical.copy()

In [194]:
numerical["LotFrontage"] = numerical["LotFrontage"].fillna(-1)

In [197]:
numerical.isna().sum()

MSSubClass     0
LotFrontage    0
LotArea        0
OverallQual    0
OverallCond    0
YearBuilt      0
dtype: int64

In [212]:
lr.score(st.transform(X_test), y_test)

0.6273709442719071

In [224]:
ohe = OneHotEncoder(sparse=False)

In [226]:
cats = ohe.fit_transform(categorical)

In [228]:
X_cat_train = cats[:1200]
X_cat_test = cats[1200:]

In [229]:
X_cat_train.shape, X_cat_test.shape

((1200, 17), (260, 17))

In [233]:
ohe.categories_

[array(['C (all)', 'FV', 'RH', 'RL', 'RM'], dtype=object),
 array(['Grvl', 'Pave'], dtype=object),
 array(['IR1', 'IR2', 'IR3', 'Reg'], dtype=object),
 array(['Bnk', 'HLS', 'Low', 'Lvl'], dtype=object),
 array(['AllPub', 'NoSeWa'], dtype=object)]

In [234]:
X_tr = np.hstack((X_train, X_cat_train))
X_te = np.hstack((X_test, X_cat_test))

In [236]:
lr = LinearRegression()

In [237]:
lr.fit(X_tr, y_train)

LinearRegression()

In [239]:
lr.score(X_te, y_test)

0.6395016352120741

# Homework

